name: choosy
description: Random item picker

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+2
  provider: ^4.0.4
  path_provider: ^1.3.0
  flutter_shake_plugin:
  uuid: ^2.0.4
  sembast:
  flutter_svg: ^0.17.3+1
  fluttertoast: ^3.1.3
  share: ^0.6.3+6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/intro.svg
    - assets/svg/missing.svg
    - assets/svg/handphone.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Regular.otf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-SemiBold.otf
          weight: 600
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.otf
          weight: 900
    - family: ChoosyIcon
      fonts:
        - asset: assets/fonts/icons/ChoosyIcon.ttf
flutter_icons:
  image_path: "assets/images/choosy-app-icon.png"
  android: true
  ios: false
