name: coolflutterapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+2
  provider: ^4.0.4
  path_provider: ^1.3.0
  flutter_shake_plugin:
  uuid: ^2.0.4
  sembast:
  flutter_slidable: "^0.5.4"
  flutter_svg: ^0.17.3+1
  dotted_border: ^1.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/intro.svg
    - assets/svg/shake.svg
    - assets/svg/missing.svg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/manrope/Manrope-Light.otf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-Regular.otf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Medium.otf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-SemiBold.otf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Bold.otf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-ExtraBold.otf
          weight: 800
    - family: Gilroy
      fonts:
        # - asset: assets/fonts/gilroy/Gilroy-Light.otf
        #   weight: 300
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.otf
          weight: 900
    - family: ChoosyIcon
      fonts:
        - asset: assets/fonts/icons/ChoosyIcon.ttf
