/// Flutter icons ChoosyIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChoosyIcon
///      fonts:
///       - asset: fonts/ChoosyIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ChoosyIcon {
  ChoosyIcon._();

  static const _kFontFam = 'ChoosyIcon';

  static const IconData add_circle_line = IconData(0xea0f, fontFamily: _kFontFam);
  static const IconData add_fill = IconData(0xea10, fontFamily: _kFontFam);
  static const IconData arrow_left_line = IconData(0xea5e, fontFamily: _kFontFam);
  static const IconData close_circle_fill = IconData(0xeb7e, fontFamily: _kFontFam);
  static const IconData close_circle_line = IconData(0xeb7f, fontFamily: _kFontFam);
  static const IconData close_fill = IconData(0xeb80, fontFamily: _kFontFam);
  static const IconData delete_bin_5_line = IconData(0xec02, fontFamily: _kFontFam);
  static const IconData edit_line = IconData(0xec52, fontFamily: _kFontFam);
  static const IconData emotion_happy_line = IconData(0xec59, fontFamily: _kFontFam);
  static const IconData more_fill = IconData(0xeefe, fontFamily: _kFontFam);
  static const IconData send_plane_2_fill = IconData(0xf03a, fontFamily: _kFontFam);
  static const IconData settings_3_line = IconData(0xf048, fontFamily: _kFontFam);
  static const IconData sound_module_fill = IconData(0xf0b3, fontFamily: _kFontFam);
  static const IconData time_line = IconData(0xf14b, fontFamily: _kFontFam);
  static const IconData timer_line = IconData(0xf151, fontFamily: _kFontFam);
  static const IconData tools_fill = IconData(0xf156, fontFamily: _kFontFam);
  static const IconData user_settings_line = IconData(0xf1a6, fontFamily: _kFontFam);
}
